title: Austin's Mini Blog
author: Austin Yang
email: ayang1@ebnet.org
description: Lil blog :D:D 
Hi! Welcome to my blog!

# social links
twitter_username: https://twitter.com/AustinY83507667
github_username:  https://github.com/ayiyang1

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
